### ISSUE TITLE
Don't loop back to the start

### ISSUE THREAD

**Issue by gmyenni** [weecology/updating-data#3]
It's confusing

Instead, end with 'you're done!' or something. And add links for other 'choose your own adventure' pathways. eg Requiring version tags on all commits.

**Comment by ethanwhite** [comment]
This is baked into the theme I used to make the site. We can turn that arrow based navigation off completely with a simple setting switch. Specifically not having the forward arrow on the last page would require hacking the theme. It's doable, but a quick gland suggests that it would probably take 2-3 hours to get everything working smoothly. I'm certainly happy to try that if we think that's the best way to go, but wanted to post the status of the work here so that folks could think about the best option given the time tradeoffs.

**Comment by gmyenni** [comment]
Oh yeah, I think we mainly just need to add a final 'you're done!' page. If it loops back after that at least it will be obvious. . . Rather than clicking through some more until you finally realize, 'wait, I've done this before! 🤔' 😆

**Comment by ethanwhite** [comment]
:+1:
